name: PopAds Adsterra Optimizer

on:
  schedule:
    - cron: "0 * * * *"   # يشغل السكربت كل ساعة
  workflow_dispatch:       # يسمح لك تشغله يدويًا من GitHub

jobs:
  run-optimizer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Run optimizer script
      env:
        POPADS_API_KEY: ${{ secrets.POPADS_API_KEY }}
        POPADS_API_SECRET: ${{ secrets.POPADS_API_SECRET }}
        ADSTERRA_API_KEY: ${{ secrets.ADSTERRA_API_KEY }}
        DATE_RANGE: "today"
        MIN_IMPRESSIONS: "100"
        MIN_COST_USD: "0.05"
        ROI_CUTOFF: "-10"
        DRY_RUN: "true"
        AUTO_EXCLUDE: "false"
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: |
        python popads_adsterra_optimizer.py
